/**
 * Site Configuration — generated by SiteAssembler
 * Design: brief-composed-a-1790666221371 (brief-composed)
 * DO NOT EDIT MANUALLY
 */

export interface NavCategory {
  name: string;
  slug: string;
}

export interface ComponentVariantConfig {
  variant: string;
  options?: Record<string, unknown>;
}

export interface RecipeSlot {
  id: string;
  kind: string;
  block: string;
  span?: string;
  limit?: number;
  categorySlug?: string;
  options?: Record<string, unknown>;
}

export interface HomepageRecipe {
  schemaVersion: 'recipe-v1';
  id: string;
  page: 'homepage';
  homepageLayout?: string;
  rhythmId?: string;
  slots: RecipeSlot[];
  grid?: 'single' | 'main-sidebar' | 'mosaic-12' | 'scoreboard-split';
}

export type HeaderFamily =
  | 'broadcast-scoreboard'
  | 'editorial-centered'
  | 'newsroom-command'
  | 'regional-utility'
  | 'visual-trending'
  | 'business-markets';

export type FooterFamily =
  | 'sports-clubhouse'
  | 'editorial-statement'
  | 'dense-directory'
  | 'regional-service'
  | 'compact-newsroom';

export interface ChromeConfig {
  schemaVersion: 'chrome-v1';
  header: {
    family: HeaderFamily;
    brandPosition: 'left' | 'center' | 'split';
    navPosition: 'inside-main' | 'below-main' | 'none';
    breakingPosition: 'top' | 'below-nav' | 'inside-header' | 'none';
    searchMode: 'icon' | 'expanded' | 'hidden';
    stickyMode: 'full' | 'compact' | 'nav-only' | 'none';
    logoScale: 'compact' | 'standard' | 'masthead';
    edgeStyle: 'flat' | 'bordered' | 'layered';
    motionProfile: 'minimal' | 'editorial' | 'energetic';
    signatureModule:
      | 'live-score-indicator'
      | 'breaking-command-strip'
      | 'region-selector'
      | 'edition-date'
      | 'trending-carousel'
      | 'market-pulse'
      | 'none';
    surface: 'dark' | 'light';
  };
  footer: {
    family: FooterFamily;
    brandScale: 'small' | 'medium' | 'large';
    backgroundTreatment: 'solid' | 'split' | 'tonal';
    columnRhythm: 'balanced' | 'asymmetric' | 'stacked';
    showNewsletter: boolean;
    showSocialWall: boolean;
    showPopularTopics: boolean;
    showAppPromotion: boolean;
  };
}

export interface SiteConfig {
  siteName: string;
  tagline: string;
  description: string;
  locale: {
    language: string;
    dialect: string;
    timezone: string;
  };
  cms: {
    baseUrl: string;
    websiteKey: string;
    collections: string[];
  };
  seo: {
    canonicalHost?: string;
    defaultOgImage: string;
  };
  layouts: {
    homepage: string;
    category: string;
    article: string;
    search: string;
  };
  density: 'high' | 'balanced' | 'low';
  motion: 'none' | 'restrained' | 'moderate' | 'energetic';
  components: {
    header: ComponentVariantConfig;
    breakingNews: ComponentVariantConfig;
    featuredCard: ComponentVariantConfig;
    standardCard: ComponentVariantConfig;
    footer: ComponentVariantConfig;
  };
  navCategories: NavCategory[];
  competitions?: Array<{
    slug: string;
    name: string;
    leagueId: number;
    season: number;
    kind: 'league' | 'cup' | 'national';
    teamId?: number;
  }>;
  homepageRecipe?: HomepageRecipe;
  componentRegistry?: {
    version: 1;
    updatedAt: string;
    blocks: Array<{
      blockId: string;
      kind: string;
      baseBlock: string;
      displayName: string;
      options?: Record<string, unknown>;
      wrapperClass?: string;
    }>;
  };
  capabilities?: {
    enabled: string[];
  };
  chrome?: ChromeConfig;
  integrations?: {
    ARTICLES_LIST?: string;
    ARTICLE_BY_SLUG?: string;
    BANNERS?: string;
    FOOTBALL_LIVE?: string;
    FOOTBALL_FIXTURES?: string;
    FOOTBALL_STANDINGS?: string;
    FOOTBALL_SCORERS?: string;
    FOOTBALL_TEAMS?: string;
    FOOTBALL_LEAGUES?: string;
    MARKETS?: string;
  };
}

export const siteConfig: SiteConfig = {
  siteName: "Chute do Interior",
  tagline: "O futebol que nasce longe dos holofotes",
  description: "O futebol que nasce longe dos holofotes",
  locale: {"language":"pt","dialect":"pt-BR","timezone":"America/Sao_Paulo"},
  cms: {
    baseUrl: process.env.NEXT_PUBLIC_CMS_URL || 'https://api.chutedointerior.com/api',
    websiteKey: process.env.NEXT_PUBLIC_CMS_WEBSITE || 'chutedointerior.com',
    collections: ["feed_brazil","aiarticles"],
  },
  seo: {
    defaultOgImage: "/og-image.jpg",
  },
  layouts: {
    "homepage": "brief-composed",
    "category": "section-led-grid",
    "article": "media-rich-story",
    "search": "editorial-results"
  },
  density: "balanced",
  motion: "restrained",
  components: {
    "header": {
      "variant": "mega-nav",
      "options": {
        "showWeather": true
      }
    },
    "breakingNews": {
      "variant": "static-banner",
      "options": {
        "interval": 5000
      }
    },
    "featuredCard": {
      "variant": "balanced-card",
      "options": {
        "showCategory": true
      }
    },
    "standardCard": {
      "variant": "horizontal-balanced"
    },
    "footer": {
      "variant": "minimal-links",
      "options": {
        "showLocalLinks": true
      }
    }
  },
  navCategories: [
    { name: "Série C", slug: "serie-c" },
    { name: "Histórias regionais", slug: "historias-regionais" },
    { name: "Base e amador", slug: "base-e-amador" },
    { name: "Série B", slug: "serie-b" },
    { name: "Brasileirão", slug: "brasileirao" },
    { name: "Copa do Brasil", slug: "copa-do-brasil" },
    { name: "Libertadores", slug: "libertadores" },
    { name: "Seleção", slug: "selecao" },
    { name: "Estados", slug: "estados" },
    { name: "Calendário", slug: "calendario" },
    { name: "Tabela de posições", slug: "tabela-de-posicoes" },
    { name: "Transferências", slug: "transferencias" },
    { name: "Partidas", slug: "partidas" },
    { name: "Clubes", slug: "clubes" },
    { name: "Jogadores", slug: "jogadores" },
    { name: "Notícias", slug: "noticias" },
    { name: "Outras", slug: "outras" }
  ],
  competitions: [
    {
      "slug": "brasileirao",
      "name": "Brasileirão",
      "leagueId": 71,
      "season": 2026,
      "kind": "league"
    },
    {
      "slug": "serie-b",
      "name": "Série B",
      "leagueId": 72,
      "season": 2026,
      "kind": "league"
    },
    {
      "slug": "copa-do-brasil",
      "name": "Copa do Brasil",
      "leagueId": 73,
      "season": 2026,
      "kind": "cup"
    },
    {
      "slug": "libertadores",
      "name": "Libertadores",
      "leagueId": 13,
      "season": 2026,
      "kind": "cup"
    },
    {
      "slug": "selecao",
      "name": "Seleção",
      "leagueId": 34,
      "season": 2026,
      "teamId": 6,
      "kind": "national"
    }
  ],
  homepageRecipe: {
    "schemaVersion": "recipe-v1",
    "id": "brief-brief-composed-a-1790666221371-a",
    "page": "homepage",
    "homepageLayout": "brief-composed",
    "rhythmId": "rhythm-mosaic-discovery",
    "grid": "mosaic-12",
    "slots": [
      {
        "id": "lead",
        "kind": "hero",
        "block": "HeroMagazine",
        "span": "full",
        "limit": 1,
        "options": {
          "source": "brief"
        }
      },
      {
        "id": "latest-rail",
        "kind": "ranked-rail",
        "block": "RankedRail",
        "span": "full",
        "limit": 5,
        "options": {}
      },
      {
        "id": "ultimas",
        "kind": "stream",
        "block": "HorizontalStream",
        "limit": 8,
        "options": {}
      },
      {
        "id": "estados-or-cats",
        "kind": "discovery-chips",
        "block": "DiscoveryChips",
        "limit": 12,
        "options": {
          "label": "Estados"
        }
      },
      {
        "id": "nacional",
        "kind": "section-pair",
        "block": "DualSection",
        "limit": 2,
        "options": {}
      },
      {
        "id": "ao-vivo-scores",
        "kind": "scoreboard",
        "block": "ScoreboardStrip",
        "limit": 3,
        "options": {
          "label": "Ao vivo"
        }
      },
      {
        "id": "mais-lidas",
        "kind": "most-read",
        "block": "MostReadPanel",
        "limit": 5,
        "options": {}
      },
      {
        "id": "newsletter",
        "kind": "newsletter",
        "block": "NewsletterCard",
        "options": {}
      }
    ]
  },
  componentRegistry: {
    "version": 1,
    "updatedAt": "2026-07-30T00:00:00.000Z",
    "blocks": []
  },
  capabilities: {
    "enabled": [
      "breaking-ticker",
      "search",
      "category-nav",
      "newsletter",
      "trending",
      "states-directory",
      "live-scores",
      "author-pages",
      "tag-pages"
    ]
  },
  chrome: {
    "schemaVersion": "chrome-v1",
    "header": {
      "family": "visual-trending",
      "brandPosition": "left",
      "navPosition": "below-main",
      "breakingPosition": "none",
      "searchMode": "expanded",
      "stickyMode": "compact",
      "logoScale": "standard",
      "edgeStyle": "layered",
      "motionProfile": "energetic",
      "signatureModule": "trending-carousel",
      "surface": "light"
    },
    "footer": {
      "family": "editorial-statement",
      "brandScale": "large",
      "backgroundTreatment": "tonal",
      "columnRhythm": "stacked",
      "showNewsletter": true,
      "showSocialWall": false,
      "showPopularTopics": false,
      "showAppPromotion": false
    }
  },
  integrations: {
    "FOOTBALL_LIVE": "/football/live",
    "FOOTBALL_FIXTURES": "/football/fixtures?league=71&season=2026",
    "FOOTBALL_STANDINGS": "/football/standings?league=71&season=2026",
    "FOOTBALL_SCORERS": "/football/topscorers?league=71&season=2026",
    "FOOTBALL_TEAMS": "/football/teams?league=71&season=2026",
    "FOOTBALL_LEAGUES": "/football/leagues",
    "MARKETS": "TODO_MARKETS_API",
    "ARTICLES_LIST": "/ai-articles?targetWebsite=chutedointerior.com&endpoint=HomePage&limit=20&page=1&sort=createdAt&order=desc",
    "ARTICLE_BY_SLUG": "/ai-articles/slug/{slug}?targetWebsite=chutedointerior.com",
    "BANNERS": "/banners/public/chutedointerior.com"
  },
};
